module MegaBar
  class Engine < ::Rails::Engine
    isolate_namespace MegaBar
    require 'seed_dump'
    require 'best_in_place'
    require 'acts_as_list'

    config.autoload_paths << File.expand_path("../*", __FILE__)

    require File.expand_path('../mega_route.rb', __FILE__)

    require File.expand_path('../layout_engine.rb', __FILE__)
    config.app_middleware.use LayoutEngine

    initializer :append_migrations do |app|
      unless app.root.to_s.match root.to_s
        config.paths["db/migrate"].expanded.each do |expanded_path|
          app.config.paths["db/migrate"] << expanded_path
        end
      end
    end

    initializer "model_core.factories", :after => "factory_girl.set_factory_paths" do
      FactoryBot.definition_file_paths << File.expand_path('../../../spec/factories', __FILE__) if defined?(FactoryBot)
    end

    initializer "mega_bar.assets" do |app|
      # Rails 8 CSS assets
      app.config.assets.paths << root.join('app', 'assets', 'stylesheets')
      app.config.assets.paths << root.join('app', 'assets', 'images')
      
      # Precompile MegaBar CSS
      app.config.assets.precompile += %w( 
        mega_bar/application.css
        mega_bar/mega_bar.css 
        mega_bar/mega_block_tabs.css 
      )
    end

    initializer "mega_bar.best_in_place" do |app|
      # Configure best_in_place
      app.config.after_initialize do
        # BestInPlace is auto-configured by the gem
        # No additional configuration needed for basic functionality
      end
    end

    initializer "mega_bar.rails8_importmap", after: "importmap" do |app|
      # Configure importmap for Rails 8+ compatibility
      if defined?(Importmap::Map)
        # Set up JavaScript asset paths for the engine
        app.config.assets.paths << root.join('app', 'javascript')
        
        # Auto-pin required JavaScript dependencies
        Rails.application.config.after_initialize do
          # Pin jQuery and dependencies
          Rails.application.importmap.pin "jquery"
          Rails.application.importmap.pin "autosize"
          
          # Pin MegaBar-specific modules
          Rails.application.importmap.pin "add_jquery", to: "add_jquery.js"
          Rails.application.importmap.pin "best_in_place", to: "best_in_place.js"
          
          # Auto-generate add_jquery.js if it doesn't exist
          add_jquery_path = Rails.root.join('app', 'javascript', 'add_jquery.js')
          unless File.exist?(add_jquery_path)
            FileUtils.mkdir_p(File.dirname(add_jquery_path))
            File.write(add_jquery_path, <<~JS)
              // Auto-generated by MegaBar engine for Rails 8 compatibility
              import jquery from "jquery";
              import autosize from "autosize";
              
              // Make jQuery globally available
              window.jQuery = jquery;
              window.$ = jquery;
              
              // Make autosize available as jQuery plugin
              jquery.fn.autosize = function () {
                this.each(function () {
                  autosize(this);
                });
                return this;
              };
            JS
            Rails.logger.info "MegaBar: Created add_jquery.js file"
          end
          
          Rails.logger.info "MegaBar: Auto-pinned importmap dependencies (jquery, autosize, add_jquery, best_in_place)"
        end
        
        Rails.logger.info "MegaBar: Rails 8 importmap compatibility enabled"
      end
    end

    config.generators do |g|
      g.test_framework :rspec
      g.fixture_replacement :factory_girl, :dir => 'spec/factories'
      g.helper false
    end

    config.action_view.logger = nil
    config.annotate_rendered_view_with_filenames = false
  end
end

# class DynamicRouter
#   def self.load
#     # abort('llll diedddd')
#     MegaBar::Application.routes.draw do
#       MegaBar::Page.all.each do |pg|
#         puts "page path: " + pg.path
#         MegaBar::Layout.all.each do |layout| 
#           MegaBar::Block.all.each do | block |
#             puts "Routing #{pg.name}"
#             get "/#{pg.name}", :to => "pages#show", defaults: { id: pg.id }
#           end
#         end
#       end
#     end
#   end

#   def self.reload
#     ComingSoon::Application.routes_reloader.reload!
#   end
# end
