<% the_module_name.split('::').each do | m | %>
module <%=m %> 
<% end %>

  require 'spec_helper'
  # This spec was generated by rspec-rails when you ran the scaffold generator.
  # It demonstrates how one might use RSpec to specify the controller code that
  # was generated by Rails when you ran the scaffold generator.
  #
  # It assumes that the implementation code is generated by the rails scaffold
  # generator.  If you are using any extension libraries to generate different
  # controller code, this generated spec may or may not pass.
  #
  # It only uses APIs available in rails and/or rspec-rails.  There are a number
  # of tools you can use to make these specs even more expressive, but we're
  # sticking to rails and rspec-rails APIs to keep things simple and stable.
  #
  # Compared to earlier versions of this generator, there is very limited use of
  # stubs and message expectations in this spec.  Stubs are only used when there
  # is no simpler way to get a handle on the object needed for the example.
  # Message expectations are only used when there is no simpler way to specify
  # that an instance is receiving a specific message.

  RSpec.describe <% if the_module_name %>module <%=the_module_name%>::<% end %><%= the_controller_name %>, :type => :controller do

    # This should return the minimal set of attributes required to create a valid
    # Model. As you add validations to Model, be sure to
    # adjust the attributes here as well.
    MegaBar::Field.skip_callback("create",:after,:make_migration)
    MegaBar::Model.skip_callback("create",:after,:make_all_files)

    #variables:
    # 1 gem_path: <%= gem_path %>
    # 2 the_controller_file_name: <%= the_controller_file_name %>
    # 3 the_controller_file_path: <%= the_controller_file_path %>
    # 4 the_controller_name: <%= the_controller_name %>
    # 5 the_controller_spec_file_name: <%= the_controller_spec_file_name %>
    # 6 the_controller_spec_file_path : <%= the_controller_spec_file_path  %>
    # 7 the_factory_file_path: <%= the_factory_file_path %>
    # 8 the_model_file_name: <%= the_model_file_name %>
    # 9 the_model_file_path: <%= the_model_file_path %>
    # 10 the_module_name: <%= the_module_name %>
    # 11 the_module_path: <%= the_module_path %>
    # 12 the_route_name: <%= the_route_name %>
    # 13 the_route_path: <%= the_route_path %>
    # 14 the_table_name: <%= the_table_name %>
    # 15 use_route: <%= use_route %>

    let(:valid_attributes) {
      v = build(:<%= the_model_file_name %>)
      { id: v[:id] } # add other fields
    }

    let(:invalid_attributes) {
      # all tests using invalid_attributes marked as pending until you define this.
      i = build(:<%= the_model_file_name %>)
      { id: i[:id] } #add other required fields as nil
    }
    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # ModelsController. Be sure to keep this updated too.
    let(:valid_session) { {} }
    context "with a model " do
      before(:each) do
        create(:model, classname: '<%= classname %>', name: '<%= classname.humanize %>', tablename: '<%= the_table_name %>')
      end
      after(:each) do
        MegaBar::Model.find(1).destroy
      end
      describe "GET index" do
        it "assigns all <%= the_table_name %> as @mega_instance" do
          <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
          get :index, {<%= use_route %> model_id: 1}, valid_session
          expect(assigns(:mega_instance)).to eq([<%= the_model_file_name %>])
        end
      end

      describe "GET show" do
        it "assigns the requested <%= the_model_file_name %> as @mega_instance" do
          <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
          get :show, {<%= use_route %> model_id: 1, :id => <%= the_model_file_name %>.to_param}, valid_session
          expect(assigns(:mega_instance)).to eq([<%= the_model_file_name %>])
        end
      end
      describe "GET new" do
        it "assigns a new <%= the_model_file_name %> as @mega_instance" do
          get :new, {<%= use_route %> model_id: 1}, valid_session
          expect(assigns(:mega_instance)).to be_a_new(<%= classname %>)
        end
      end

      describe "GET edit" do
        it "assigns the requested <%= the_model_file_name %> as @mega_instance" do
          <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
          get :edit, {<%= use_route %> model_id: 1, :id => <%= the_model_file_name %>.to_param}, valid_session
          expect(assigns(:mega_instance)).to eq(<%= the_model_file_name %>)
        end
      end
    end
    context 'with a model  and fields for <%= the_model_file_name %>' do
      before(:each) do
        create(:model, classname: '<%= classname %>', name: '<%= classname %>', tablename: '<%= the_table_name %>')
        create(:field, tablename: '<%= the_table_name %>', field: 'id')
        # add additional (required) fields
      end
      after(:each) do
        MegaBar::Model.find(1).destroy
        MegaBar::Field.destroy_all
      end
      describe "POST create" do
        describe "with valid params" do
          it "creates a new <%= the_model_file_name %>" do
            expect {
              post :create, {<%= use_route %> model_id: 1, :<%= the_model_file_name %>=> valid_attributes}, valid_session
            }.to change(<%= classname %>, :count).by(1)
          end

          it "assigns a newly created <%= the_model_file_name %> as @mega_instance" do
            post :create, {<%= use_route %> model_id: 1, :<%= the_model_file_name %> => valid_attributes}, valid_session
            expect(assigns(:mega_instance)).to be_a(<%= classname %>)
            expect(assigns(:mega_instance)).to be_persisted
          end

          it "redirects to the created <%= the_model_file_name %>"  do
            post :create, {<%= use_route %> model_id: 1, :<%= the_model_file_name %> => valid_attributes}, valid_session
            expect(response).to redirect_to(<%= classname %>.last)
          end
        end

        describe "with invalid params" do
          it "assigns a newly created but unsaved <%= the_model_file_name %> as @mega_instance" do
            skip('define invalid_attributes above')
            post :create, {<%= use_route %> model_id: 1, :<%= the_model_file_name %> => invalid_attributes}, valid_session
            expect(assigns(:mega_instance)).to be_a_new(<%= classname %>)
          end

          it "re-renders the 'new' template"  do
            skip('define invalid_attributes above')
            post :create, {<%= use_route %> model_id: 1, :<%= the_model_file_name %> => invalid_attributes}, valid_session
            expect(response).to render_template('mega_bar.html.erb')
          end
        end
      end

      describe "PUT update" do
        describe "with valid params" do
          let(:new_attributes) { # marked as pending until params added here.
            md = build(:<%= the_model_file_name %>)
            { }
          }

          it "updates the requested <%= the_model_file_name %>" do
            skip('define new_attributes')
            <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
            put :update, {<%= use_route %> :id => <%= the_model_file_name %>.to_param, :<%= the_model_file_name %> => new_attributes}, valid_session
            <%= the_model_file_name %>.reload
            expect(<%= the_model_file_name %>.attributes).to include( { 'id' => "5" } )
          end

          it "assigns the requested <%= the_model_file_name %> as @mega_instance" do
            <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
            put :update, {<%= use_route %> :id => <%= the_model_file_name %>.to_param, :<%= the_model_file_name %> => valid_attributes}, valid_session
            expect(assigns(:mega_instance)).to eq(<%= the_model_file_name %>)
          end

          it "redirects to the <%= the_model_file_name %>" do
            <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
            put :update, {<%= use_route %> :id => <%= the_model_file_name %>.to_param, :<%= the_model_file_name %> => valid_attributes}, valid_session
            expect(response).to redirect_to(<%= the_model_file_name %>)
          end
        end

        describe "with invalid params" do
          it "assigns the <%= the_model_file_name %> as @mega_instance" do
            skip('define invalid_attributes above')
            <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
            put :update, {<%= use_route %> :id => <%= the_model_file_name %>.to_param, :<%= the_model_file_name %> => invalid_attributes}, valid_session
            expect(assigns(:mega_instance)).to eq(<%= the_model_file_name %>)
          end

          it "re-renders the 'edit' template" do
            skip('define invalid_attributes above')
            <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
            put :update, {<%= use_route %> :id => <%= the_model_file_name %>.to_param, :<%= the_model_file_name %> => invalid_attributes}, valid_session
            expect(response).to render_template("mega_bar.html.erb")
          end
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested <%= the_model_file_name %>" do
        <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
        expect {
          delete :destroy, {<%= use_route %> :id => <%= the_model_file_name %>.to_param}, valid_session
        }.to change(<%= classname %>, :count).by(-1)
      end

      it "redirects to the <%= the_model_file_name %> list" do
        <%= the_model_file_name %> = <%= classname %>.create! valid_attributes
        delete :destroy, {<%= use_route %> :id => <%= the_model_file_name %>.to_param}, valid_session
        expect(response).to redirect_to("/mega-bar/<%= the_route_path %>")
      end
    end

  end  
<% the_module_name.split('::').each do | m | %>
end 
<% end %>