module MegaBar
  require 'spec_helper'
  # This spec was generated by rspec-rails when you ran the scaffold generator.
  # It demonstrates how one might use RSpec to specify the controller code that
  # was generated by Rails when you ran the scaffold generator.
  #
  # It assumes that the implementation code is generated by the rails scaffold
  # generator.  If you are using any extension libraries to generate different
  # controller code, this generated spec may or may not pass.
  #
  # It only uses APIs available in rails and/or rspec-rails.  There are a number
  # of tools you can use to make these specs even more expressive, but we're
  # sticking to rails and rspec-rails APIs to keep things simple and stable.
  #
  # Compared to earlier versions of this generator, there is very limited use of
  # stubs and message expectations in this spec.  Stubs are only used when there
  # is no simpler way to get a handle on the object needed for the example.
  # Message expectations are only used when there is no simpler way to specify
  # that an instance is receiving a specific message.

  RSpec.describe MegaBar::FieldDisplaysController, :type => :controller do

    # This should return the minimal set of attributes required to create a valid
    # Model. As you add validations to Model, be sure to
    # adjust the attributes here as well.
    # model_display_id 1
    # field_id 1
    # format 'textread'
    # header 'Hi there, I am a field display'

    let(:valid_attributes) {
      f = build(:field_display)
      { header: f[:header], model_display_id: f[:model_display_id], format: f[:format], field_id: f[:field_id], id: f[:id]  }
    }

    let(:invalid_attributes) {
      f = build(:field_display)
      { header: f[:header],  model_display_id: nil, format: nil, id: f[:id]  }
    }
    
    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # ModelsController. Be sure to keep this updated too.
    let(:valid_session) { {} }
    context "with a model " do
      before(:each) do
        MegaBar::Model.skip_callback("create",:after,:make_all_files)
        MegaBar::Model.skip_callback("create",:after,:make_model_displays)    
        create(:model, classname: 'FieldDisplay', name: 'Field Display', tablename: 'field_displays')
      end
      after(:each) do
        Model.find(1).destroy
        MegaBar::Model.set_callback("create",:after,:make_all_files)
        MegaBar::Model.set_callback("create",:after,:make_model_displays)
      end
      describe "GET index", focus: true do
        it "assigns all field_displays as @mega_instance" do
          field_display = FieldDisplay.create! valid_attributes
          get :index, {use_route: :mega_bar, model_id: 1}, valid_session
          expect(assigns(:mega_instance)).to eq([field_display])
        end
      end

      describe "GET show" do
        it "assigns the requested field_display as @mega_instance" do
          field_display = FieldDisplay.create! valid_attributes
          get :show, {use_route: :mega_bar, model_id: 1, :id => field_display.to_param}, valid_session
          expect(assigns(:mega_instance)).to eq([field_display])
        end
      end
      describe "GET new" do
        it "assigns a new field_display as @mega_instance" do
          get :new, {use_route: :mega_bar, model_id: 1}, valid_session
          expect(assigns(:mega_instance)).to be_a_new(FieldDisplay)
        end
      end

      describe "GET edit" do
        it "assigns the requested field_display as @mega_instance" do
          field_display = FieldDisplay.create! valid_attributes
          get :edit, {use_route: :mega_bar, model_id: 1, :id => field_display.to_param}, valid_session
          expect(assigns(:mega_instance)).to eq(field_display)
        end
      end
    end
    context 'with a model, a record format and fields for field_displays' do
      before(:each) do
        MegaBar::Field.skip_callback("save",:after,:make_field_displays) 
        MegaBar::Field.skip_callback("create",:after,:make_field_displays)
        MegaBar::Field.skip_callback("create",:after,:make_migration)
        MegaBar::Model.skip_callback("create",:after,:make_all_files)
        MegaBar::Model.skip_callback("create",:after,:make_model_displays)
        create(:model, classname: 'FieldDisplay', tablename: 'field_displays', name: 'Field Displays')
        create(:field, tablename: 'field_display', field: 'model_display_id')
        create(:field, tablename: 'field_display', field: 'field_id')
        create(:field, tablename: 'field_display', field: 'format')
      end
      after(:each) do
        Model.find(1).destroy
        Field.destroy_all
        MegaBar::Field.set_callback("save",:after,:make_field_displays) 
        MegaBar::Field.set_callback("create",:after,:make_field_displays)
        MegaBar::Field.set_callback("create",:after,:make_migration)
        MegaBar::Model.set_callback("create",:after,:make_all_files)
        MegaBar::Model.set_callback("create",:after,:make_model_displays)
      
      end
      describe "POST create" do
        describe "with valid params" do
          it "creates a new FieldDisplay" do
            #  create(:field_for_field_model)
            expect {
              post :create, {use_route: :mega_bar, model_id: 1, :field_display=> valid_attributes}, valid_session
            }.to change(FieldDisplay, :count).by(1)
          end

          it "assigns a newly created FieldDisplay as @mega_instance" do
            post :create, {use_route: :mega_bar, model_id: 1, :field_display => valid_attributes}, valid_session
            expect(assigns(:mega_instance)).to be_a(FieldDisplay)
            expect(assigns(:mega_instance)).to be_persisted
          end

          it "redirects to the created FieldDisplay"  do
            post :create, {use_route: :mega_bar, model_id: 1, :field_display => valid_attributes}, valid_session
            expect(response).to redirect_to(FieldDisplay.last)
          end
        end

        describe "with invalid params" do
          it "assigns a newly created but unsaved FieldDisplay as @mega_instance" do
            post :create, {use_route: :mega_bar, model_id: 1, :field_display => invalid_attributes}, valid_session
            expect(assigns(:mega_instance)).to be_a_new(FieldDisplay)
          end

          it "re-renders the 'new' template"  do
            post :create, {use_route: :mega_bar, model_id: 1, :field_display => invalid_attributes}, valid_session
            expect(response).to render_template('mega_bar.html.erb')
          end
        end
      end

      describe "PUT update" do
        describe "with valid params" do
          let(:new_attributes) {
            md = build(:field_display)
            { header: md[:header], model_display_id: 3, format: 'textbox', field_id: md[:field_id], id: md[:id] }
          }

          it "updates the requested field_display" do
            field_display = FieldDisplay.create! valid_attributes
            put :update, {use_route: :mega_bar, :id => field_display.to_param, :field_display => new_attributes}, valid_session
            field_display.reload
            expect(field_display.attributes).to include( "model_display_id" => 3, "format" => 'textbox' )
          end

          it "assigns the requested field_display as @mega_instance" do
            field_display = FieldDisplay.create! valid_attributes
            put :update, {use_route: :mega_bar, :id => field_display.to_param, :field_display => valid_attributes}, valid_session
            expect(assigns(:mega_instance)).to eq(field_display)
          end

          it "redirects to the field_display" do
            field_display = FieldDisplay.create! valid_attributes
            put :update, {use_route: :mega_bar, :id => field_display.to_param, :field_display => valid_attributes}, valid_session
            expect(response).to redirect_to(field_display)
          end
        end

        describe "with invalid params" do
          it "assigns the field_display as @mega_instance" do
            field_display = FieldDisplay.create! valid_attributes
            put :update, {use_route: :mega_bar, :id => field_display.to_param, :field_display => invalid_attributes}, valid_session
            expect(assigns(:mega_instance)).to eq(field_display)
          end

          it "re-renders the 'edit' template" do
            field_display = FieldDisplay.create! valid_attributes
            put :update, {use_route: :mega_bar, :id => field_display.to_param, :field_display => invalid_attributes}, valid_session
            expect(response).to render_template("mega_bar.html.erb")
          end
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested field_display" do
        field_display = FieldDisplay.create! valid_attributes
        expect {
          delete :destroy, {use_route: :mega_bar, :id => field_display.to_param}, valid_session
        }.to change(FieldDisplay, :count).by(-1)
      end

      it "redirects to the field_display list" do
        field_display = FieldDisplay.create! valid_attributes
        delete :destroy, {use_route: :mega_bar, :id => field_display.to_param}, valid_session
        expect(response).to redirect_to("/mega-bar/" + url_for('field_displays'))
      end
    end

  end
end