
module MegaBar 

  puts "Did you remember to copy the migration over to the megabar db/migrate directory?"
  require 'spec_helper'
  # This spec was generated by rspec-rails when you ran the scaffold generator.
  # It demonstrates how one might use RSpec to specify the controller code that
  # was generated by Rails when you ran the scaffold generator.
  #
  # It assumes that the implementation code is generated by the rails scaffold
  # generator.  If you are using any extension libraries to generate different
  # controller code, this generated spec may or may not pass.
  #
  # It only uses APIs available in rails and/or rspec-rails.  There are a number
  # of tools you can use to make these specs even more expressive, but we're
  # sticking to rails and rspec-rails APIs to keep things simple and stable.
  #
  # Compared to earlier versions of this generator, there is very limited use of
  # stubs and message expectations in this spec.  Stubs are only used when there
  # is no simpler way to get a handle on the object needed for the example.
  # Message expectations are only used when there is no simpler way to specify
  # that an instance is receiving a specific message.

  RSpec.describe MegaBar::ModelDisplayFormatsController, :type => :controller do

    # This should return the minimal set of attributes required to create a valid
    # Model. As you add validations to Model, be sure to
    # adjust the attributes here as well.
    MegaBar::Field.skip_callback("create",:after,:make_migration)
    MegaBar::Model.skip_callback("create",:after,:make_all_files)

    #variables:
    # 1 gem_path: /Users/bagus/websites/megabar/
    # 2 the_controller_file_name: model_display_formats_controller
    # 3 the_controller_file_path: app/controllers/mega_bar/
    # 4 the_controller_name: ModelDisplayFormatsController
    # 5 the_controller_spec_file_name: model_display_formats_controller_spec
    # 6 the_controller_spec_file_path : spec/controllers/
    # 7 the_factory_file_path: spec/internal/factories/
    # 8 the_model_file_name: model_display_format
    # 9 the_model_file_path: app/models/mega_bar/
    # 10 the_module_name: MegaBar
    # 11 the_module_path: mega_bar
    # 12 the_route_name: model_display_formats
    # 13 the_route_path: model-display-formats
    # 14 the_table_name: mega_bar_model_display_formats
    # 15 use_route: use_route: MegaBar, 

    let(:valid_attributes) {
      v = build(:model_display_format)
      { id: v[:id] } # add other fields
    }

    let(:invalid_attributes) {
      # all tests using invalid_attributes marked as pending until you define this.
      i = build(:model_display_format)
      { id: i[:id] } #add other required fields as nil
    }
    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # ModelsController. Be sure to keep this updated too.
    let(:valid_session) { {} }
    context "with a model " do
      before(:each) do
        create(:model, classname: 'ModelDisplayFormat', name: 'Modeldisplayformat', tablename: 'mega_bar_model_display_formats')
      end
      after(:each) do
        MegaBar::Model.find(1).destroy
      end
      describe "GET index" do
        it "assigns all mega_bar_model_display_formats as @mega_instance" do
          model_display_format = ModelDisplayFormat.create! valid_attributes
          get :index, {use_route: MegaBar,  model_id: 1}, valid_session
          expect(assigns(:mega_instance)).to eq([model_display_format])
        end
      end

      describe "GET show" do
        it "assigns the requested model_display_format as @mega_instance" do
          model_display_format = ModelDisplayFormat.create! valid_attributes
          get :show, {use_route: MegaBar,  model_id: 1, :id => model_display_format.to_param}, valid_session
          expect(assigns(:mega_instance)).to eq([model_display_format])
        end
      end
      describe "GET new" do
        it "assigns a new model_display_format as @mega_instance" do
          get :new, {use_route: MegaBar,  model_id: 1}, valid_session
          expect(assigns(:mega_instance)).to be_a_new(ModelDisplayFormat)
        end
      end

      describe "GET edit" do
        it "assigns the requested model_display_format as @mega_instance" do
          model_display_format = ModelDisplayFormat.create! valid_attributes
          get :edit, {use_route: MegaBar,  model_id: 1, :id => model_display_format.to_param}, valid_session
          expect(assigns(:mega_instance)).to eq(model_display_format)
        end
      end
    end
    context 'with a model  and fields for model_display_format' do
      before(:each) do
        create(:model, classname: 'ModelDisplayFormat', name: 'ModelDisplayFormat', tablename: 'mega_bar_model_display_formats')
        create(:field, tablename: 'mega_bar_model_display_formats', field: 'id')
        # add additional (required) fields
      end
      after(:each) do
        MegaBar::Model.find(1).destroy
        MegaBar::Field.destroy_all
      end
      describe "POST create" do
        describe "with valid params" do
          it "creates a new model_display_format" do
            expect {
              post :create, {use_route: MegaBar,  model_id: 1, :model_display_format=> valid_attributes}, valid_session
            }.to change(ModelDisplayFormat, :count).by(1)
          end

          it "assigns a newly created model_display_format as @mega_instance" do
            post :create, {use_route: MegaBar,  model_id: 1, :model_display_format => valid_attributes}, valid_session
            expect(assigns(:mega_instance)).to be_a(ModelDisplayFormat)
            expect(assigns(:mega_instance)).to be_persisted
          end

          it "redirects to the created model_display_format"  do
            post :create, {use_route: MegaBar,  model_id: 1, :model_display_format => valid_attributes}, valid_session
            expect(response).to redirect_to(ModelDisplayFormat.last)
          end
        end

        describe "with invalid params" do
          it "assigns a newly created but unsaved model_display_format as @mega_instance" do
            skip('define invalid_attributes above')
            post :create, {use_route: MegaBar,  model_id: 1, :model_display_format => invalid_attributes}, valid_session
            expect(assigns(:mega_instance)).to be_a_new(ModelDisplayFormat)
          end

          it "re-renders the 'new' template"  do
            skip('define invalid_attributes above')
            post :create, {use_route: MegaBar,  model_id: 1, :model_display_format => invalid_attributes}, valid_session
            expect(response).to render_template('mega_bar.html.erb')
          end
        end
      end

      describe "PUT update" do
        describe "with valid params" do
          let(:new_attributes) { # marked as pending until params added here.
            md = build(:model_display_format)
            { }
          }

          it "updates the requested model_display_format" do
            skip('define new_attributes')
            model_display_format = ModelDisplayFormat.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => model_display_format.to_param, :model_display_format => new_attributes}, valid_session
            model_display_format.reload
            expect(model_display_format.attributes).to include( { 'id' => "5" } )
          end

          it "assigns the requested model_display_format as @mega_instance" do
            model_display_format = ModelDisplayFormat.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => model_display_format.to_param, :model_display_format => valid_attributes}, valid_session
            expect(assigns(:mega_instance)).to eq(model_display_format)
          end

          it "redirects to the model_display_format" do
            model_display_format = ModelDisplayFormat.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => model_display_format.to_param, :model_display_format => valid_attributes}, valid_session
            expect(response).to redirect_to(model_display_format)
          end
        end

        describe "with invalid params" do
          it "assigns the model_display_format as @mega_instance" do
            skip('define invalid_attributes above')
            model_display_format = ModelDisplayFormat.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => model_display_format.to_param, :model_display_format => invalid_attributes}, valid_session
            expect(assigns(:mega_instance)).to eq(model_display_format)
          end

          it "re-renders the 'edit' template" do
            skip('define invalid_attributes above')
            model_display_format = ModelDisplayFormat.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => model_display_format.to_param, :model_display_format => invalid_attributes}, valid_session
            expect(response).to render_template("mega_bar.html.erb")
          end
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested model_display_format" do
        model_display_format = ModelDisplayFormat.create! valid_attributes
        expect {
          delete :destroy, {use_route: MegaBar,  :id => model_display_format.to_param}, valid_session
        }.to change(ModelDisplayFormat, :count).by(-1)
      end

      it "redirects to the model_display_format list" do
        model_display_format = ModelDisplayFormat.create! valid_attributes
        delete :destroy, {use_route: MegaBar,  :id => model_display_format.to_param}, valid_session
        expect(response).to redirect_to("/mega-bar/model-display-formats")
      end
    end

  end  

end 
