
module MegaBar 

  puts "Did you remember to copy the migration over to the megabar db/migrate directory?"
  require 'spec_helper'
  # This spec was generated by rspec-rails when you ran the scaffold generator.
  # It demonstrates how one might use RSpec to specify the controller code that
  # was generated by Rails when you ran the scaffold generator.
  #
  # It assumes that the implementation code is generated by the rails scaffold
  # generator.  If you are using any extension libraries to generate different
  # controller code, this generated spec may or may not pass.
  #
  # It only uses APIs available in rails and/or rspec-rails.  There are a number
  # of tools you can use to make these specs even more expressive, but we're
  # sticking to rails and rspec-rails APIs to keep things simple and stable.
  #
  # Compared to earlier versions of this generator, there is very limited use of
  # stubs and message expectations in this spec.  Stubs are only used when there
  # is no simpler way to get a handle on the object needed for the example.
  # Message expectations are only used when there is no simpler way to specify
  # that an instance is receiving a specific message.

  RSpec.describe MegaBar::SandsController, :type => :controller do

    # This should return the minimal set of attributes required to create a valid
    # Model. As you add validations to Model, be sure to
    # adjust the attributes here as well.
    MegaBar::Field.skip_callback("create",:after,:make_migration)
    MegaBar::Model.skip_callback("create",:after,:make_all_files)

    #variables:
    # 1 gem_path: /Users/bagus/websites/megabar/
    # 2 the_controller_file_name: sands_controller
    # 3 the_controller_file_path: app/controllers/mega_bar/
    # 4 the_controller_name: SandsController
    # 5 the_controller_spec_file_name: sands_controller_spec
    # 6 the_controller_spec_file_path : spec/controllers/
    # 7 the_factory_file_path: spec/internal/factories/
    # 8 the_model_file_name: sand
    # 9 the_model_file_path: app/models/mega_bar/
    # 10 the_module_name: MegaBar
    # 11 the_module_path: mega_bar
    # 12 the_route_name: sands
    # 13 the_route_path: sands
    # 14 the_table_name: mega_bar_sands
    # 15 use_route: use_route: MegaBar, 

    let(:valid_attributes) {
      v = build(:sand)
      { id: v[:id] } # add other fields
    }

    let(:invalid_attributes) {
      # all tests using invalid_attributes marked as pending until you define this.
      i = build(:sand)
      { id: i[:id] } #add other required fields as nil
    }
    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # ModelsController. Be sure to keep this updated too.
    let(:valid_session) { {} }
    context "with a model " do
      before(:each) do
        create(:model, classname: 'Sand', name: 'Sand', tablename: 'mega_bar_sands')
      end
      after(:each) do
        MegaBar::Model.find(1).destroy
      end
      describe "GET index" do
        it "assigns all mega_bar_sands as @mega_instance" do
          sand = Sand.create! valid_attributes
          get :index, {use_route: MegaBar,  model_id: 1}, valid_session
          expect(assigns(:mega_instance)).to eq([sand])
        end
      end

      describe "GET show" do
        it "assigns the requested sand as @mega_instance" do
          sand = Sand.create! valid_attributes
          get :show, {use_route: MegaBar,  model_id: 1, :id => sand.to_param}, valid_session
          expect(assigns(:mega_instance)).to eq([sand])
        end
      end
      describe "GET new" do
        it "assigns a new sand as @mega_instance" do
          get :new, {use_route: MegaBar,  model_id: 1}, valid_session
          expect(assigns(:mega_instance)).to be_a_new(Sand)
        end
      end

      describe "GET edit" do
        it "assigns the requested sand as @mega_instance" do
          sand = Sand.create! valid_attributes
          get :edit, {use_route: MegaBar,  model_id: 1, :id => sand.to_param}, valid_session
          expect(assigns(:mega_instance)).to eq(sand)
        end
      end
    end
    context 'with a model  and fields for sand' do
      before(:each) do
        create(:model, classname: 'Sand', name: 'Sand', tablename: 'mega_bar_sands')
        create(:field, tablename: 'mega_bar_sands', field: 'id')
        # add additional (required) fields
      end
      after(:each) do
        MegaBar::Model.find(1).destroy
        MegaBar::Field.destroy_all
      end
      describe "POST create" do
        describe "with valid params" do
          it "creates a new sand" do
            expect {
              post :create, {use_route: MegaBar,  model_id: 1, :sand=> valid_attributes}, valid_session
            }.to change(Sand, :count).by(1)
          end

          it "assigns a newly created sand as @mega_instance" do
            post :create, {use_route: MegaBar,  model_id: 1, :sand => valid_attributes}, valid_session
            expect(assigns(:mega_instance)).to be_a(Sand)
            expect(assigns(:mega_instance)).to be_persisted
          end

          it "redirects to the created sand"  do
            post :create, {use_route: MegaBar,  model_id: 1, :sand => valid_attributes}, valid_session
            expect(response).to redirect_to(Sand.last)
          end
        end

        describe "with invalid params" do
          it "assigns a newly created but unsaved sand as @mega_instance" do
            skip('define invalid_attributes above')
            post :create, {use_route: MegaBar,  model_id: 1, :sand => invalid_attributes}, valid_session
            expect(assigns(:mega_instance)).to be_a_new(Sand)
          end

          it "re-renders the 'new' template"  do
            skip('define invalid_attributes above')
            post :create, {use_route: MegaBar,  model_id: 1, :sand => invalid_attributes}, valid_session
            expect(response).to render_template('mega_bar.html.erb')
          end
        end
      end

      describe "PUT update" do
        describe "with valid params" do
          let(:new_attributes) { # marked as pending until params added here.
            md = build(:sand)
            { }
          }

          it "updates the requested sand" do
            skip('define new_attributes')
            sand = Sand.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => sand.to_param, :sand => new_attributes}, valid_session
            sand.reload
            expect(sand.attributes).to include( { 'id' => "5" } )
          end

          it "assigns the requested sand as @mega_instance" do
            sand = Sand.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => sand.to_param, :sand => valid_attributes}, valid_session
            expect(assigns(:mega_instance)).to eq(sand)
          end

          it "redirects to the sand" do
            sand = Sand.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => sand.to_param, :sand => valid_attributes}, valid_session
            expect(response).to redirect_to(sand)
          end
        end

        describe "with invalid params" do
          it "assigns the sand as @mega_instance" do
            skip('define invalid_attributes above')
            sand = Sand.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => sand.to_param, :sand => invalid_attributes}, valid_session
            expect(assigns(:mega_instance)).to eq(sand)
          end

          it "re-renders the 'edit' template" do
            skip('define invalid_attributes above')
            sand = Sand.create! valid_attributes
            put :update, {use_route: MegaBar,  :id => sand.to_param, :sand => invalid_attributes}, valid_session
            expect(response).to render_template("mega_bar.html.erb")
          end
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested sand" do
        sand = Sand.create! valid_attributes
        expect {
          delete :destroy, {use_route: MegaBar,  :id => sand.to_param}, valid_session
        }.to change(Sand, :count).by(-1)
      end

      it "redirects to the sand list" do
        sand = Sand.create! valid_attributes
        delete :destroy, {use_route: MegaBar,  :id => sand.to_param}, valid_session
        expect(response).to redirect_to("/mega-bar/sands")
      end
    end

  end  

end 
